# Generated by Django 5.2.4 on 2025-09-18 20:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_allowedorigin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Face Analyzer', max_length=200)),
                ('body', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('usage_duration_days', models.IntegerField(default=0)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('offline_token', models.TextField(blank=True, null=True)),
                ('online_token', models.TextField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('theme_editor_link', models.URLField(blank=True, null=True)),
                ('metafield_definition_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
