# Generated by Django 5.2.4 on 2025-10-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_pagecontent_purchase_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
