# Generated by Django 5.2.4 on 2025-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_purchase_phone_alter_purchase_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceanalysis',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
