# Generated by Django 5.2.4 on 2026-01-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_faceanalysis_domain_purchase_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(default='Face Analyzer', max_length=500),
        ),
        migrations.AlterField(
            model_name='shop',
            name='theme_editor_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
