# Generated by Django 5.2.4 on 2026-02-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_alter_pagecontent_title_alter_shop_theme_editor_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='analysis_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
