# Generated by Django 5.2.4 on 2026-01-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordpressShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(unique=True)),
                ('admin_email', models.EmailField(max_length=254)),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_limit', models.IntegerField(default=100)),
                ('analysis_this_month', models.IntegerField(default=0)),
                ('analysis_all_time', models.BigIntegerField(default=0)),
                ('wp_version', models.CharField(blank=True, max_length=10)),
                ('plugin_version', models.CharField(blank=True, max_length=10)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
