# Generated by Django 5.2.4 on 2026-01-06 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordPress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20, unique=True)),
                ('monthly_limit', models.IntegerField(default=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='wordpressshop',
            name='monthly_limit',
        ),
        migrations.RemoveField(
            model_name='wordpressshop',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='wordpressshop',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wordPress.plan'),
        ),
    ]
